image: docker.io/atlassian/default-image:5

pipelines:
  default:
    - step:
        name: Secrets Scan
        script:
          - pipe: atlassian/git-secrets-scan:3.2.0

    - parallel:
        - step:
            name: Build Runner JAR
            image: docker.io/library/eclipse-temurin:21-jdk
            clone:
              enabled: true
            caches:
              - maven
            script:
              - ./mvnw --batch-mode verify -DskipITs
            artifacts:
              - target/quoteweaver-*-runner.jar
            after-script:
              - if [ "$BITBUCKET_EXIT_CODE" -ne 0 ]; then
                echo "[ERROR] Build failed, skipping artifact upload."
                return 1
              - fi
              - SANITIZED_BRANCH_NAME=$(echo "$BITBUCKET_BRANCH" | sed 's/[^a-zA-Z0-9_]/_/g')
              - JAR_FILE_PATH=$(ls target/quoteweaver-*-runner.jar)
              - JAR_FILE=$(basename "$JAR_FILE_PATH")
              - TAR_BALL_NAME="quoteweaver-${SANITIZED_BRANCH_NAME}-$BITBUCKET_BUILD_NUMBER-runner-jar.tar.gz"
              - tar -czf "$TAR_BALL_NAME" -C "$(dirname "$JAR_FILE_PATH")" "$JAR_FILE"
              - pipe: atlassian/bitbucket-upload-file:0.7.4
                variables:
                  BITBUCKET_ACCESS_TOKEN: "$BITPIPE"
                  FILENAME: "$TAR_BALL_NAME"

        - step:
            name: Build Native Executable
            image: quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21
            size: 2x
            clone:
              enabled: true
            caches:
              - maven
            script:
              - ./mvnw --batch-mode verify -Dnative -DskipITs
            artifacts:
              - target/quoteweaver-*-runner
            after-script:
              - if [ "$BITBUCKET_EXIT_CODE" -ne 0 ]; then
                echo "[ERROR] Build failed, skipping artifact upload."
                return 1
              - fi
              - SANITIZED_BRANCH_NAME=$(echo "$BITBUCKET_BRANCH" | sed 's/[^a-zA-Z0-9_]/_/g')
              - NATIVE_FILE_PATH=$(ls target/quoteweaver-*-runner)
              - NATIVE_FILE=$(basename "$NATIVE_FILE_PATH")
              - TAR_BALL_NAME="quoteweaver-${SANITIZED_BRANCH_NAME}-$BITBUCKET_BUILD_NUMBER-native-executable.tar.gz"
              - tar -czf "$TAR_BALL_NAME" -C "$(dirname "$NATIVE_FILE_PATH")" "$NATIVE_FILE"
              - pipe: atlassian/bitbucket-upload-file:0.7.4
                variables:
                  BITBUCKET_ACCESS_TOKEN: "$BITPIPE"
                  FILENAME: "$TAR_BALL_NAME"
